[project]
name = "deephy"
version = "0.4.0"
authors = [
    { name = "Matt Groth", email = "mjgroth@mit.edu" },
]
dependencies = [
    'cbor2',
    'numpy',
    'torch'
]
[project.urls]
"Homepage" = "https://github.com/mgroth0/deephy"
"Bug Tracker" = "https://github.com/mgroth0/deephy/issues"